function MX011ums1 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  MX011UMS1 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the numeric data.
%
%  MX011UMS1 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  MX011ums1 = importfile("C:\Users\augus\Downloads\DMA_MX_fiber\MX01\MX01_1ums-1.txt", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-Feb-2021 20:58:01

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Time", "TotalForce", "TotalDisplacement"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
MX011ums1 = readtable(filename, opts);

%% Convert to output type
MX011ums1 = table2array(MX011ums1);
end